services:
  postgres:
    image: postgres:16.3
    container_name: isolve-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: isolve_db
      POSTGRES_USER: isolve_admin
      POSTGRES_PASSWORD: change_this_password
    ports:
      - "5432:5432"
    volumes:
      - isolve-postgres-data:/var/lib/postgresql/data
    networks:
      - isolve-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U isolve_admin"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

volumes:
  isolve-postgres-data:

networks:
  isolve-network:
    driver: bridge