spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/isolve_db}
    username: ${SPRING_DATASOURCE_USERNAME:isolve_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:change_this_password}
    driver-class-name: org.postgresql.Driver

  flyway:
    clean-on-validation-error: true

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}